import {
  FieldType,
  OnDeleteAction,
  RelationType,
  STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS,
  defineObject,
} from 'twenty-sdk/define';

import {
  BOOKING,
  COMMUNICATION,
  CONTACT_METHOD,
  PERSON_FIELDS,
  PROPERTY,
  SERVICE_EVENT,
  SOURCE_RECORD,
  TASK_BOOKING_FIELD,
  WHATSAPP_CONTACT_WATCH,
} from 'src/constants/identifiers';

export default defineObject({
  universalIdentifier: BOOKING.object,
  nameSingular: 'booking',
  namePlural: 'bookings',
  labelSingular: 'Booking',
  labelPlural: 'Bookings',
  description: 'Canonical operational record for a stay or service engagement.',
  icon: 'IconCalendarCheck',
  isSearchable: true,
  labelIdentifierFieldMetadataUniversalIdentifier: BOOKING.fields.name,
  fields: [
    {
      universalIdentifier: BOOKING.fields.name,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Booking',
      icon: 'IconCalendarCheck',
    },
    {
      universalIdentifier: BOOKING.fields.bookingId,
      type: FieldType.UUID,
      name: 'bookingId',
      label: 'Booking ID',
      icon: 'IconFingerprint',
      isUnique: true,
    },
    {
      universalIdentifier: BOOKING.fields.source,
      type: FieldType.SELECT,
      name: 'source',
      label: 'Source',
      icon: 'IconDatabaseImport',
      defaultValue: "'MANUAL'",
      options: [
        { value: 'WHATSAPP', label: 'WhatsApp', position: 0, color: 'green' },
        { value: 'TALKGUEST', label: 'TalkGuest', position: 1, color: 'blue' },
        { value: 'EMAIL', label: 'Email', position: 2, color: 'orange' },
        { value: 'MANUAL', label: 'Manual', position: 3, color: 'gray' },
        { value: 'KAIROS', label: 'Kairos', position: 4, color: 'purple' },
        { value: 'FUTURE_API', label: 'Future API', position: 5, color: 'turquoise' },
      ],
    },
    {
      universalIdentifier: BOOKING.fields.externalBookingId,
      type: FieldType.TEXT,
      name: 'externalBookingId',
      label: 'External booking ID',
      icon: 'IconId',
      isNullable: true,
    },
    {
      universalIdentifier: BOOKING.fields.sourceKey,
      type: FieldType.TEXT,
      name: 'sourceKey',
      label: 'Source key',
      description: 'Unique source plus external ID key used for idempotent ingestion.',
      icon: 'IconKey',
      isUnique: true,
    },
    {
      universalIdentifier: BOOKING.fields.sourceUrl,
      type: FieldType.LINKS,
      name: 'sourceUrl',
      label: 'Source URL',
      icon: 'IconLink',
      isNullable: true,
    },
    {
      universalIdentifier: BOOKING.fields.sourceLastSeenAt,
      type: FieldType.DATE_TIME,
      name: 'sourceLastSeenAt',
      label: 'Source last seen at',
      icon: 'IconClock',
      isNullable: true,
    },
    {
      universalIdentifier: BOOKING.fields.guest,
      type: FieldType.RELATION,
      name: 'guest',
      label: 'Guest',
      icon: 'IconUser',
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier:
        STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS.person.universalIdentifier,
      relationTargetFieldMetadataUniversalIdentifier:
        PERSON_FIELDS.guestBookings,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.SET_NULL,
        joinColumnName: 'guestId',
      },
    },
    {
      universalIdentifier: BOOKING.fields.property,
      type: FieldType.RELATION,
      name: 'property',
      label: 'Property',
      icon: 'IconBuildingEstate',
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier: PROPERTY.object,
      relationTargetFieldMetadataUniversalIdentifier: PROPERTY.fields.bookings,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.SET_NULL,
        joinColumnName: 'propertyId',
      },
    },
    {
      universalIdentifier: BOOKING.fields.contactMethods,
      type: FieldType.RELATION,
      name: 'contactMethods',
      label: 'Booking contact methods',
      icon: 'IconAddressBook',
      relationTargetObjectMetadataUniversalIdentifier: CONTACT_METHOD.object,
      relationTargetFieldMetadataUniversalIdentifier:
        CONTACT_METHOD.fields.booking,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
    {
      universalIdentifier: BOOKING.fields.preferredContactMethod,
      type: FieldType.RELATION,
      name: 'preferredContactMethod',
      label: 'Preferred booking contact',
      icon: 'IconPhoneCheck',
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier: CONTACT_METHOD.object,
      relationTargetFieldMetadataUniversalIdentifier:
        CONTACT_METHOD.fields.preferredForBookings,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.SET_NULL,
        joinColumnName: 'preferredContactMethodId',
      },
    },
    {
      universalIdentifier: BOOKING.fields.serviceEvents,
      type: FieldType.RELATION,
      name: 'serviceEvents',
      label: 'Service events',
      icon: 'IconCalendarEvent',
      relationTargetObjectMetadataUniversalIdentifier: SERVICE_EVENT.object,
      relationTargetFieldMetadataUniversalIdentifier:
        SERVICE_EVENT.fields.booking,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
    {
      universalIdentifier: BOOKING.fields.communications,
      type: FieldType.RELATION,
      name: 'communications',
      label: 'Communications',
      icon: 'IconMessages',
      relationTargetObjectMetadataUniversalIdentifier: COMMUNICATION.object,
      relationTargetFieldMetadataUniversalIdentifier:
        COMMUNICATION.fields.booking,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
    {
      universalIdentifier: BOOKING.fields.whatsappContactWatches,
      type: FieldType.RELATION,
      name: 'whatsappContactWatches',
      label: 'WhatsApp contact watches',
      icon: 'IconBrandWhatsapp',
      relationTargetObjectMetadataUniversalIdentifier:
        WHATSAPP_CONTACT_WATCH.object,
      relationTargetFieldMetadataUniversalIdentifier:
        WHATSAPP_CONTACT_WATCH.fields.booking,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
    {
      universalIdentifier: BOOKING.fields.sourceRecords,
      type: FieldType.RELATION,
      name: 'sourceRecords',
      label: 'Source records',
      icon: 'IconDatabase',
      relationTargetObjectMetadataUniversalIdentifier: SOURCE_RECORD.object,
      relationTargetFieldMetadataUniversalIdentifier:
        SOURCE_RECORD.fields.booking,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
    {
      universalIdentifier: BOOKING.fields.tasks,
      type: FieldType.RELATION,
      name: 'tasks',
      label: 'Tasks',
      icon: 'IconChecklist',
      relationTargetObjectMetadataUniversalIdentifier:
        STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS.task.universalIdentifier,
      relationTargetFieldMetadataUniversalIdentifier: TASK_BOOKING_FIELD,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
    {
      universalIdentifier: BOOKING.fields.checkinAt,
      type: FieldType.DATE_TIME,
      name: 'checkinAt',
      label: 'Check-in at',
      icon: 'IconLogin2',
      isNullable: true,
    },
    {
      universalIdentifier: BOOKING.fields.checkoutAt,
      type: FieldType.DATE_TIME,
      name: 'checkoutAt',
      label: 'Check-out at',
      icon: 'IconLogout2',
      isNullable: true,
    },
    {
      universalIdentifier: BOOKING.fields.arrivalWindowStart,
      type: FieldType.DATE_TIME,
      name: 'arrivalWindowStart',
      label: 'Arrival window start',
      icon: 'IconClockPlay',
      isNullable: true,
    },
    {
      universalIdentifier: BOOKING.fields.arrivalWindowEnd,
      type: FieldType.DATE_TIME,
      name: 'arrivalWindowEnd',
      label: 'Arrival window end',
      icon: 'IconClockStop',
      isNullable: true,
    },
    {
      universalIdentifier: BOOKING.fields.timezone,
      type: FieldType.TEXT,
      name: 'timezone',
      label: 'Timezone',
      icon: 'IconWorld',
      defaultValue: "'Europe/Lisbon'",
    },
    {
      universalIdentifier: BOOKING.fields.status,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      icon: 'IconProgressCheck',
      defaultValue: "'NEW'",
      options: [
        { value: 'NEW', label: 'New', position: 0, color: 'gray' },
        { value: 'CONFIRMED', label: 'Confirmed', position: 1, color: 'blue' },
        { value: 'PREPARING', label: 'Preparing', position: 2, color: 'orange' },
        { value: 'WAITING_FOR_GUEST', label: 'Waiting for Guest', position: 3, color: 'yellow' },
        { value: 'READY', label: 'Ready', position: 4, color: 'green' },
        { value: 'IN_PROGRESS', label: 'In Progress', position: 5, color: 'turquoise' },
        { value: 'COMPLETED', label: 'Completed', position: 6, color: 'green' },
        { value: 'CANCELLED', label: 'Cancelled', position: 7, color: 'gray' },
        { value: 'PROBLEM', label: 'Problem', position: 8, color: 'red' },
      ],
    },
    {
      universalIdentifier: BOOKING.fields.readinessStatus,
      type: FieldType.SELECT,
      name: 'readinessStatus',
      label: 'Readiness',
      icon: 'IconClipboardCheck',
      defaultValue: "'UNKNOWN'",
      options: [
        { value: 'UNKNOWN', label: 'Unknown', position: 0, color: 'gray' },
        { value: 'MISSING_CONTACT', label: 'Missing Contact', position: 1, color: 'red' },
        { value: 'MISSING_LOCATION', label: 'Missing Location', position: 2, color: 'red' },
        { value: 'MISSING_ARRIVAL_DETAILS', label: 'Missing Arrival Details', position: 3, color: 'orange' },
        { value: 'READY', label: 'Ready', position: 4, color: 'green' },
        { value: 'NEEDS_REVIEW', label: 'Needs Review', position: 5, color: 'yellow' },
      ],
    },
    {
      universalIdentifier: BOOKING.fields.riskLevel,
      type: FieldType.SELECT,
      name: 'riskLevel',
      label: 'Risk level',
      icon: 'IconAlertTriangle',
      defaultValue: "'LOW'",
      options: [
        { value: 'LOW', label: 'Low', position: 0, color: 'green' },
        { value: 'MEDIUM', label: 'Medium', position: 1, color: 'yellow' },
        { value: 'HIGH', label: 'High', position: 2, color: 'orange' },
        { value: 'CRITICAL', label: 'Critical', position: 3, color: 'red' },
      ],
    },
    {
      universalIdentifier: BOOKING.fields.needsHumanReview,
      type: FieldType.BOOLEAN,
      name: 'needsHumanReview',
      label: 'Needs human review',
      icon: 'IconUserQuestion',
      defaultValue: false,
    },
    {
      universalIdentifier: BOOKING.fields.missingInformation,
      type: FieldType.TEXT,
      name: 'missingInformation',
      label: 'Missing information',
      icon: 'IconListCheck',
      isNullable: true,
    },
    {
      universalIdentifier: BOOKING.fields.lastReviewedAt,
      type: FieldType.DATE_TIME,
      name: 'lastReviewedAt',
      label: 'Last reviewed at',
      icon: 'IconClockCheck',
      isNullable: true,
    },
    {
      universalIdentifier: BOOKING.fields.aiSummary,
      type: FieldType.TEXT,
      name: 'aiSummary',
      label: 'AI summary',
      description: 'Convenience summary; never authoritative.',
      icon: 'IconSparkles',
      isNullable: true,
    },
    {
      universalIdentifier: BOOKING.fields.internalNotes,
      type: FieldType.TEXT,
      name: 'internalNotes',
      label: 'Internal notes',
      icon: 'IconNotes',
      isNullable: true,
    },
    {
      universalIdentifier: BOOKING.fields.specialInstructions,
      type: FieldType.TEXT,
      name: 'specialInstructions',
      label: 'Special instructions',
      icon: 'IconInfoCircle',
      isNullable: true,
    },
    {
      universalIdentifier: BOOKING.fields.rawMetadata,
      type: FieldType.RAW_JSON,
      name: 'rawMetadata',
      label: 'Raw metadata',
      icon: 'IconJson',
      isNullable: true,
    },
  ],
});
