import {
  FieldType,
  OnDeleteAction,
  RelationType,
  STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS,
  defineObject,
} from 'twenty-sdk/define';

import {
  BOOKING,
  CONTACT_METHOD,
  PERSON_FIELDS,
  SOURCE_RECORD,
} from 'src/constants/identifiers';

export default defineObject({
  universalIdentifier: CONTACT_METHOD.object,
  nameSingular: 'bookingContactMethod',
  namePlural: 'bookingContactMethods',
  labelSingular: 'Booking Contact Method',
  labelPlural: 'Booking Contact Methods',
  description: 'Booking-scoped contact candidates with independent provenance.',
  icon: 'IconAddressBook',
  isSearchable: true,
  labelIdentifierFieldMetadataUniversalIdentifier: CONTACT_METHOD.fields.name,
  fields: [
    {
      universalIdentifier: CONTACT_METHOD.fields.name,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Contact label',
      icon: 'IconAddressBook',
    },
    {
      universalIdentifier: CONTACT_METHOD.fields.sourceContactKey,
      type: FieldType.TEXT,
      name: 'sourceContactKey',
      label: 'Source contact key',
      description: 'Stable booking plus source plus contact identity.',
      icon: 'IconKey',
      isUnique: true,
    },
    {
      universalIdentifier: CONTACT_METHOD.fields.booking,
      type: FieldType.RELATION,
      name: 'booking',
      label: 'Booking',
      icon: 'IconCalendarCheck',
      relationTargetObjectMetadataUniversalIdentifier: BOOKING.object,
      relationTargetFieldMetadataUniversalIdentifier:
        BOOKING.fields.contactMethods,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.CASCADE,
        joinColumnName: 'bookingId',
      },
    },
    {
      universalIdentifier: CONTACT_METHOD.fields.person,
      type: FieldType.RELATION,
      name: 'person',
      label: 'Person',
      icon: 'IconUser',
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier:
        STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS.person.universalIdentifier,
      relationTargetFieldMetadataUniversalIdentifier:
        PERSON_FIELDS.bookingContactMethods,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.SET_NULL,
        joinColumnName: 'personId',
      },
    },
    {
      universalIdentifier: CONTACT_METHOD.fields.contactType,
      type: FieldType.SELECT,
      name: 'contactType',
      label: 'Contact type',
      icon: 'IconMessageCircle',
      options: [
        { value: 'WHATSAPP', label: 'WhatsApp', position: 0, color: 'green' },
        { value: 'PHONE', label: 'Phone', position: 1, color: 'blue' },
        { value: 'EMAIL', label: 'Email', position: 2, color: 'orange' },
        { value: 'OTHER', label: 'Other', position: 3, color: 'gray' },
      ],
    },
    {
      universalIdentifier: CONTACT_METHOD.fields.contactValue,
      type: FieldType.TEXT,
      name: 'contactValue',
      label: 'Contact value',
      icon: 'IconAt',
    },
    {
      universalIdentifier: CONTACT_METHOD.fields.source,
      type: FieldType.SELECT,
      name: 'source',
      label: 'Source',
      icon: 'IconDatabaseImport',
      options: [
        { value: 'WHATSAPP', label: 'WhatsApp', position: 0, color: 'green' },
        { value: 'TALKGUEST', label: 'TalkGuest', position: 1, color: 'blue' },
        { value: 'MANUAL', label: 'Manual', position: 2, color: 'gray' },
        { value: 'EMAIL', label: 'Email', position: 3, color: 'orange' },
        { value: 'OTHER', label: 'Other', position: 4, color: 'purple' },
      ],
    },
    {
      universalIdentifier: CONTACT_METHOD.fields.sourceRecord,
      type: FieldType.RELATION,
      name: 'sourceRecord',
      label: 'Source record',
      icon: 'IconDatabase',
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier: SOURCE_RECORD.object,
      relationTargetFieldMetadataUniversalIdentifier:
        SOURCE_RECORD.fields.contactMethods,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.SET_NULL,
        joinColumnName: 'sourceRecordId',
      },
    },
    {
      universalIdentifier: CONTACT_METHOD.fields.priority,
      type: FieldType.NUMBER,
      name: 'priority',
      label: 'Priority',
      icon: 'IconSortAscendingNumbers',
      defaultValue: 100,
    },
    {
      universalIdentifier: CONTACT_METHOD.fields.isPreferred,
      type: FieldType.BOOLEAN,
      name: 'isPreferred',
      label: 'Preferred',
      icon: 'IconStar',
      defaultValue: false,
    },
    {
      universalIdentifier: CONTACT_METHOD.fields.preferenceMode,
      type: FieldType.SELECT,
      name: 'preferenceMode',
      label: 'Preference mode',
      description: 'Distinguishes policy selection from an explicit human choice.',
      icon: 'IconAdjustments',
      defaultValue: "'POLICY'",
      options: [
        { value: 'POLICY', label: 'Policy', position: 0, color: 'blue' },
        { value: 'MANUAL', label: 'Manual', position: 1, color: 'purple' },
      ],
    },
    {
      universalIdentifier: CONTACT_METHOD.fields.confidence,
      type: FieldType.SELECT,
      name: 'confidence',
      label: 'Confidence',
      icon: 'IconShieldCheck',
      defaultValue: "'UNVERIFIED'",
      options: [
        { value: 'CONFIRMED', label: 'Confirmed', position: 0, color: 'green' },
        { value: 'LIKELY', label: 'Likely', position: 1, color: 'yellow' },
        { value: 'UNVERIFIED', label: 'Unverified', position: 2, color: 'gray' },
      ],
    },
    {
      universalIdentifier: CONTACT_METHOD.fields.lastVerifiedAt,
      type: FieldType.DATE_TIME,
      name: 'lastVerifiedAt',
      label: 'Last verified at',
      icon: 'IconClockCheck',
      isNullable: true,
    },
    {
      universalIdentifier: CONTACT_METHOD.fields.validFrom,
      type: FieldType.DATE_TIME,
      name: 'validFrom',
      label: 'Valid from',
      icon: 'IconCalendarPlus',
      isNullable: true,
    },
    {
      universalIdentifier: CONTACT_METHOD.fields.validUntil,
      type: FieldType.DATE_TIME,
      name: 'validUntil',
      label: 'Valid until',
      icon: 'IconCalendarMinus',
      isNullable: true,
    },
    {
      universalIdentifier: CONTACT_METHOD.fields.notes,
      type: FieldType.TEXT,
      name: 'notes',
      label: 'Notes',
      icon: 'IconNotes',
      isNullable: true,
    },
    {
      universalIdentifier: CONTACT_METHOD.fields.preferredForBookings,
      type: FieldType.RELATION,
      name: 'preferredForBookings',
      label: 'Preferred for bookings',
      icon: 'IconStar',
      relationTargetObjectMetadataUniversalIdentifier: BOOKING.object,
      relationTargetFieldMetadataUniversalIdentifier:
        BOOKING.fields.preferredContactMethod,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
  ],
});
