import {
  FieldType,
  RelationType,
  defineObject,
} from 'twenty-sdk/define';

import { BOOKING, PROPERTY } from 'src/constants/identifiers';

export default defineObject({
  universalIdentifier: PROPERTY.object,
  nameSingular: 'property',
  namePlural: 'properties',
  labelSingular: 'Property',
  labelPlural: 'Properties',
  description: 'Operational locations served by Kairos.',
  icon: 'IconBuildingEstate',
  isSearchable: true,
  labelIdentifierFieldMetadataUniversalIdentifier: PROPERTY.fields.name,
  fields: [
    {
      universalIdentifier: PROPERTY.fields.name,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Name',
      icon: 'IconBuildingEstate',
    },
    {
      universalIdentifier: PROPERTY.fields.externalPropertyId,
      type: FieldType.TEXT,
      name: 'externalPropertyId',
      label: 'External property ID',
      icon: 'IconFingerprint',
      isNullable: true,
      isUnique: true,
    },
    {
      universalIdentifier: PROPERTY.fields.propertyAddress,
      type: FieldType.TEXT,
      name: 'propertyAddress',
      label: 'Address',
      icon: 'IconMapPin',
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY.fields.mapUrl,
      type: FieldType.LINKS,
      name: 'mapUrl',
      label: 'Map URL',
      icon: 'IconMap',
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY.fields.defaultCheckinNotes,
      type: FieldType.TEXT,
      name: 'defaultCheckinNotes',
      label: 'Default check-in notes',
      icon: 'IconNotes',
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY.fields.accessNotes,
      type: FieldType.TEXT,
      name: 'accessNotes',
      label: 'Access notes',
      description: 'Non-secret access context only.',
      icon: 'IconDoorEnter',
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY.fields.accessSecretReference,
      type: FieldType.TEXT,
      name: 'accessSecretReference',
      label: 'Access secret reference',
      description: 'Opaque reference to a secret store; never a raw credential.',
      icon: 'IconKey',
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY.fields.active,
      type: FieldType.BOOLEAN,
      name: 'active',
      label: 'Active',
      icon: 'IconToggleRight',
      defaultValue: true,
    },
    {
      universalIdentifier: PROPERTY.fields.timezone,
      type: FieldType.TEXT,
      name: 'timezone',
      label: 'Timezone',
      description: 'IANA timezone, for example Europe/Lisbon.',
      icon: 'IconWorld',
      defaultValue: "'Europe/Lisbon'",
    },
    {
      universalIdentifier: PROPERTY.fields.metadata,
      type: FieldType.RAW_JSON,
      name: 'metadata',
      label: 'Metadata',
      icon: 'IconJson',
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY.fields.bookings,
      type: FieldType.RELATION,
      name: 'bookings',
      label: 'Bookings',
      icon: 'IconCalendarEvent',
      relationTargetObjectMetadataUniversalIdentifier: BOOKING.object,
      relationTargetFieldMetadataUniversalIdentifier: BOOKING.fields.property,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
  ],
});
