import {
  FieldType,
  OnDeleteAction,
  RelationType,
  defineObject,
} from 'twenty-sdk/define';

import { BOOKING, SERVICE_EVENT } from 'src/constants/identifiers';

export default defineObject({
  universalIdentifier: SERVICE_EVENT.object,
  nameSingular: 'serviceEvent',
  namePlural: 'serviceEvents',
  labelSingular: 'Service Event',
  labelPlural: 'Service Events',
  description: 'Canonical operational and calendar events for bookings.',
  icon: 'IconCalendarEvent',
  isSearchable: true,
  labelIdentifierFieldMetadataUniversalIdentifier: SERVICE_EVENT.fields.title,
  fields: [
    {
      universalIdentifier: SERVICE_EVENT.fields.title,
      type: FieldType.TEXT,
      name: 'title',
      label: 'Title',
      icon: 'IconCalendarEvent',
    },
    {
      universalIdentifier: SERVICE_EVENT.fields.sourceEventKey,
      type: FieldType.TEXT,
      name: 'sourceEventKey',
      label: 'Source event key',
      description: 'Stable source key used to make event upserts idempotent.',
      icon: 'IconKey',
      isUnique: true,
    },
    {
      universalIdentifier: SERVICE_EVENT.fields.booking,
      type: FieldType.RELATION,
      name: 'booking',
      label: 'Booking',
      icon: 'IconCalendarCheck',
      relationTargetObjectMetadataUniversalIdentifier: BOOKING.object,
      relationTargetFieldMetadataUniversalIdentifier:
        BOOKING.fields.serviceEvents,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.CASCADE,
        joinColumnName: 'bookingId',
      },
    },
    {
      universalIdentifier: SERVICE_EVENT.fields.eventType,
      type: FieldType.SELECT,
      name: 'eventType',
      label: 'Event type',
      icon: 'IconCategory',
      options: [
        { value: 'GUEST_CONTACT_DEADLINE', label: 'Guest contact deadline', position: 0, color: 'orange' },
        { value: 'DAY_BEFORE_PREPARATION', label: 'Day-before preparation', position: 1, color: 'yellow' },
        { value: 'CHECK_IN', label: 'Check-in', position: 2, color: 'green' },
        { value: 'KEY_HANDOVER', label: 'Key handover', position: 3, color: 'blue' },
        { value: 'FOLLOW_UP', label: 'Follow-up', position: 4, color: 'turquoise' },
        { value: 'CHECK_OUT', label: 'Check-out', position: 5, color: 'purple' },
        { value: 'CUSTOM', label: 'Custom', position: 6, color: 'gray' },
      ],
    },
    {
      universalIdentifier: SERVICE_EVENT.fields.startsAt,
      type: FieldType.DATE_TIME,
      name: 'startsAt',
      label: 'Starts at',
      icon: 'IconClockPlay',
    },
    {
      universalIdentifier: SERVICE_EVENT.fields.endsAt,
      type: FieldType.DATE_TIME,
      name: 'endsAt',
      label: 'Ends at',
      icon: 'IconClockStop',
      isNullable: true,
    },
    {
      universalIdentifier: SERVICE_EVENT.fields.status,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      icon: 'IconProgressCheck',
      defaultValue: "'SCHEDULED'",
      options: [
        { value: 'SCHEDULED', label: 'Scheduled', position: 0, color: 'blue' },
        { value: 'READY', label: 'Ready', position: 1, color: 'green' },
        { value: 'IN_PROGRESS', label: 'In Progress', position: 2, color: 'turquoise' },
        { value: 'COMPLETED', label: 'Completed', position: 3, color: 'green' },
        { value: 'CANCELLED', label: 'Cancelled', position: 4, color: 'gray' },
        { value: 'PROBLEM', label: 'Problem', position: 5, color: 'red' },
      ],
    },
    {
      universalIdentifier: SERVICE_EVENT.fields.location,
      type: FieldType.TEXT,
      name: 'location',
      label: 'Location',
      icon: 'IconMapPin',
      isNullable: true,
    },
    {
      universalIdentifier: SERVICE_EVENT.fields.notes,
      type: FieldType.TEXT,
      name: 'notes',
      label: 'Notes',
      icon: 'IconNotes',
      isNullable: true,
    },
    {
      universalIdentifier: SERVICE_EVENT.fields.source,
      type: FieldType.SELECT,
      name: 'source',
      label: 'Source',
      icon: 'IconDatabaseImport',
      defaultValue: "'KAIROS'",
      options: [
        { value: 'WHATSAPP', label: 'WhatsApp', position: 0, color: 'green' },
        { value: 'TALKGUEST', label: 'TalkGuest', position: 1, color: 'blue' },
        { value: 'EMAIL', label: 'Email', position: 2, color: 'orange' },
        { value: 'MANUAL', label: 'Manual', position: 3, color: 'gray' },
        { value: 'KAIROS', label: 'Kairos', position: 4, color: 'purple' },
        { value: 'FUTURE_API', label: 'Future API', position: 5, color: 'turquoise' },
      ],
    },
    {
      universalIdentifier: SERVICE_EVENT.fields.externalEventId,
      type: FieldType.TEXT,
      name: 'externalEventId',
      label: 'External event ID',
      icon: 'IconId',
      isNullable: true,
    },
    {
      universalIdentifier: SERVICE_EVENT.fields.kairosRemindersEnabled,
      type: FieldType.BOOLEAN,
      name: 'kairosRemindersEnabled',
      label: 'Kairos reminders enabled',
      icon: 'IconBell',
      defaultValue: true,
    },
    {
      universalIdentifier: SERVICE_EVENT.fields.externalCalendarProvider,
      type: FieldType.TEXT,
      name: 'externalCalendarProvider',
      label: 'Calendar provider',
      icon: 'IconCalendarCog',
      isNullable: true,
    },
    {
      universalIdentifier: SERVICE_EVENT.fields.externalCalendarId,
      type: FieldType.TEXT,
      name: 'externalCalendarId',
      label: 'External calendar ID',
      icon: 'IconCalendar',
      isNullable: true,
    },
    {
      universalIdentifier: SERVICE_EVENT.fields.externalCalendarEventId,
      type: FieldType.TEXT,
      name: 'externalCalendarEventId',
      label: 'External calendar event ID',
      icon: 'IconCalendarEvent',
      isNullable: true,
    },
    {
      universalIdentifier: SERVICE_EVENT.fields.lastCalendarSyncAt,
      type: FieldType.DATE_TIME,
      name: 'lastCalendarSyncAt',
      label: 'Last calendar sync at',
      icon: 'IconRefresh',
      isNullable: true,
    },
    {
      universalIdentifier: SERVICE_EVENT.fields.calendarSyncStatus,
      type: FieldType.SELECT,
      name: 'calendarSyncStatus',
      label: 'Calendar sync status',
      icon: 'IconCloudCheck',
      defaultValue: "'NOT_CONFIGURED'",
      options: [
        { value: 'NOT_CONFIGURED', label: 'Not configured', position: 0, color: 'gray' },
        { value: 'PENDING', label: 'Pending', position: 1, color: 'yellow' },
        { value: 'SYNCED', label: 'Synced', position: 2, color: 'green' },
        { value: 'ERROR', label: 'Error', position: 3, color: 'red' },
      ],
    },
  ],
});
