import {
  FieldType,
  OnDeleteAction,
  RelationType,
  defineObject,
} from 'twenty-sdk/define';

import {
  BOOKING,
  COMMUNICATION,
  CONTACT_METHOD,
  SOURCE_RECORD,
} from 'src/constants/identifiers';

export default defineObject({
  universalIdentifier: SOURCE_RECORD.object,
  nameSingular: 'sourceRecord',
  namePlural: 'sourceRecords',
  labelSingular: 'Source Record',
  labelPlural: 'Source Records',
  description: 'Immutable-ish ingestion evidence and parser provenance.',
  icon: 'IconDatabase',
  isSearchable: true,
  labelIdentifierFieldMetadataUniversalIdentifier: SOURCE_RECORD.fields.name,
  fields: [
    {
      universalIdentifier: SOURCE_RECORD.fields.name,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Source record',
      icon: 'IconDatabase',
    },
    {
      universalIdentifier: SOURCE_RECORD.fields.sourceType,
      type: FieldType.SELECT,
      name: 'sourceType',
      label: 'Source type',
      icon: 'IconDatabaseImport',
      options: [
        { value: 'WHATSAPP', label: 'WhatsApp', position: 0, color: 'green' },
        { value: 'TALKGUEST', label: 'TalkGuest', position: 1, color: 'blue' },
        { value: 'EMAIL', label: 'Email', position: 2, color: 'orange' },
        { value: 'MANUAL', label: 'Manual', position: 3, color: 'gray' },
        { value: 'KAIROS', label: 'Kairos', position: 4, color: 'purple' },
        { value: 'FUTURE_API', label: 'Future API', position: 5, color: 'turquoise' },
      ],
    },
    {
      universalIdentifier: SOURCE_RECORD.fields.externalId,
      type: FieldType.TEXT,
      name: 'externalId',
      label: 'External ID',
      icon: 'IconId',
    },
    {
      universalIdentifier: SOURCE_RECORD.fields.sourceKey,
      type: FieldType.TEXT,
      name: 'sourceKey',
      label: 'Source key',
      description: 'Unique source plus external ID key for replay safety.',
      icon: 'IconKey',
      isUnique: true,
    },
    {
      universalIdentifier: SOURCE_RECORD.fields.receivedAt,
      type: FieldType.DATE_TIME,
      name: 'receivedAt',
      label: 'Received at',
      icon: 'IconClockDown',
    },
    {
      universalIdentifier: SOURCE_RECORD.fields.sourceTimestamp,
      type: FieldType.DATE_TIME,
      name: 'sourceTimestamp',
      label: 'Source timestamp',
      icon: 'IconClock',
      isNullable: true,
    },
    {
      universalIdentifier: SOURCE_RECORD.fields.booking,
      type: FieldType.RELATION,
      name: 'booking',
      label: 'Booking',
      icon: 'IconCalendarCheck',
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier: BOOKING.object,
      relationTargetFieldMetadataUniversalIdentifier:
        BOOKING.fields.sourceRecords,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.SET_NULL,
        joinColumnName: 'bookingId',
      },
    },
    {
      universalIdentifier: SOURCE_RECORD.fields.contactMethods,
      type: FieldType.RELATION,
      name: 'contactMethods',
      label: 'Contact methods',
      icon: 'IconAddressBook',
      relationTargetObjectMetadataUniversalIdentifier: CONTACT_METHOD.object,
      relationTargetFieldMetadataUniversalIdentifier:
        CONTACT_METHOD.fields.sourceRecord,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
    {
      universalIdentifier: SOURCE_RECORD.fields.communications,
      type: FieldType.RELATION,
      name: 'communications',
      label: 'Communications',
      icon: 'IconMessages',
      relationTargetObjectMetadataUniversalIdentifier: COMMUNICATION.object,
      relationTargetFieldMetadataUniversalIdentifier:
        COMMUNICATION.fields.rawSourceRecord,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
    {
      universalIdentifier: SOURCE_RECORD.fields.parseStatus,
      type: FieldType.SELECT,
      name: 'parseStatus',
      label: 'Parse status',
      icon: 'IconCode',
      defaultValue: "'RECEIVED'",
      options: [
        { value: 'RECEIVED', label: 'Received', position: 0, color: 'blue' },
        { value: 'PARSED', label: 'Parsed', position: 1, color: 'turquoise' },
        { value: 'RECONCILED', label: 'Reconciled', position: 2, color: 'green' },
        { value: 'NEEDS_REVIEW', label: 'Needs Review', position: 3, color: 'yellow' },
        { value: 'ERROR', label: 'Error', position: 4, color: 'red' },
      ],
    },
    {
      universalIdentifier: SOURCE_RECORD.fields.contentHash,
      type: FieldType.TEXT,
      name: 'contentHash',
      label: 'Content hash',
      icon: 'IconHash',
      isNullable: true,
    },
    {
      universalIdentifier: SOURCE_RECORD.fields.rawText,
      type: FieldType.TEXT,
      name: 'rawText',
      label: 'Raw text',
      description: 'Operational source content only; never credentials or session state.',
      icon: 'IconFileText',
      isNullable: true,
    },
    {
      universalIdentifier: SOURCE_RECORD.fields.rawMetadata,
      type: FieldType.RAW_JSON,
      name: 'rawMetadata',
      label: 'Raw metadata',
      icon: 'IconJson',
      isNullable: true,
    },
    {
      universalIdentifier: SOURCE_RECORD.fields.parserVersion,
      type: FieldType.TEXT,
      name: 'parserVersion',
      label: 'Parser version',
      icon: 'IconVersions',
      isNullable: true,
    },
    {
      universalIdentifier: SOURCE_RECORD.fields.error,
      type: FieldType.TEXT,
      name: 'error',
      label: 'Error',
      icon: 'IconAlertTriangle',
      isNullable: true,
    },
  ],
});
